# This file is automatically generated by Jina executor normalizer plugin.
# It is not intended for manual editing.

# ATTENTION: ARG before FROM will be invalid in the statements after FROM tag
ARG ARG_BASE_IMAGE
FROM ${ARG_BASE_IMAGE}

ARG ARG_JINA_VERSION
ARG ARG_PIP_JINA_VERSION
ARG ARG_DOCARRAY_VERSION
ARG ARG_BUILD_DATE
# the following label use ARG hence will invalid the cache
LABEL org.opencontainers.image.created=${ARG_BUILD_DATE} \
      org.opencontainers.image.source="https://github.com/jina-ai/jina/commit/refs/tags/${ARG_JINA_VERSION}" \
      org.opencontainers.image.version=${ARG_JINA_VERSION} \
      org.opencontainers.image.revision=refs/tags/${ARG_JINA_VERSION}

# the following env use ARG hence will invalid the cache
ENV JINA_VERSION=${ARG_JINA_VERSION} \
    JINA_VCS_VERSION=refs/tags/${ARG_JINA_VERSION} \
    JINA_BUILD_DATE=${ARG_BUILD_DATE}

# There is a history bug in Jina core.
# Both JINA_PIP_INSTALL_CORE and JINA_PIP_INSTALL_PERF were set no matter in any cases
# https://github.com/jina-ai/jina/pull/3673
RUN unset JINA_PIP_INSTALL_CORE && \
    unset JINA_PIP_INSTALL_PERF

ENV JINA_PIP_INSTALL_PERF=1

# Need to uninstall jina first when upgrading 2.x to 3.x
# https://github.com/jina-ai/jina/issues/4194
RUN pip uninstall -y jina && pip install --upgrade ${ARG_PIP_JINA_VERSION}
RUN if [ -n "$ARG_DOCARRAY_VERSION" ] && [ "$ARG_DOCARRAY_VERSION" != "undefined" ] ; then \
    pip uninstall -y docarray && pip install --upgrade docarray==${ARG_DOCARRAY_VERSION} ; \
    fi
ENTRYPOINT ["jina", "executor", "--uses", "config.yml"]
