FROM jinaai/jina:2.0-perf

COPY . /workspace
WORKDIR /workspace

RUN --mount=type=secret,id=AUTH_TOKEN --mount=type=secret,id=TOKEN export AUTH_TOKEN="$(cat /run/secrets/AUTH_TOKEN)" export TOKEN="$(cat /run/secrets/TOKEN)"  &&   pip install --no-cache-dir -r requirements.txt

ENTRYPOINT ["jina", "executor", "--uses", "config.yml"]
