# This file is automatically generated by Jina executor normalizer plugin.
# It is not intended for manual editing.

FROM jinaai/jina:master-perf

ENTRYPOINT ["jina", "executor", "--uses", "config.yml"]
