name: Release and tag

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    # Semver release based on conventional commits
    - name: Prepare local repository
      run: git fetch --prune --unshallow --tags -f
    - name: semver-releaser
      uses: heyvito/semver-releaser@v0.0.8
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
