name: Release

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install requirements
        run: make init
      - name: Run tests
        run: pytest --cov=normalizer --cov=generator  --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml

  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Install semantic-release
        run: npm install --global semantic-release @semantic-release/git
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.JINA_DEV_BOT_TOKEN }}
          GH_TOKEN: ${{ secrets.JINA_DEV_BOT_TOKEN }}
        run: npx semantic-release
